### PR TITLE
Fix for the xla/test error that happens with rocm ci_build

### PR DESCRIPTION
**Pull request by parallelo**

### CODE REVIEW

**Comment by parallelo** [comment]
The goal of this PR is to fix some xla build errors that are blocking our CI efforts.  

We'll see how tonight's CI build+test goes, but my own by-hand tests show the following: 
```
Executed 346 out of 346 tests: 346 tests pass.
```

In other words, this PR should fix the following build errors:
```
ERROR: workspace/tensorflow/compiler/xla/tests/build_defs.bzl:23:8: syntax error at 'if': expected :
ERROR: workspace/tensorflow/compiler/xla/tests/build_defs.bzl:26:25: missing else clause in conditional expression or semicolon before if.
ERROR: workspace/tensorflow/compiler/xla/tests/build_defs.bzl:110:3: Trailing comma is allowed only in parenthesized tuples.
ERROR: workspace/tensorflow/compiler/xla/tests/build_defs.bzl:150:1: syntax error at 'outdent': expected expression.
ERROR: workspace/tensorflow/compiler/xla/tests/build_defs.bzl:152:2: indentation error.
ERROR: package contains errors: tensorflow/compiler/xla/tests.
...
All tests passed but there were other errors during the build.
```

**Comment by whchung** [comment]
@parallelo The more I look into this PR the more I think this could be a bug in upstream TF. More info to follow.

**Comment by whchung** [comment]
CI logs shows:
```
//tensorflow/python/feature_column:feature_column_test                   [0m[31m[1mFAILED[0m in 1 out of 2 in 11.9s
```

The fix in `build_defs.bzl` is legit though.

**Comment by parallelo** [comment]
Yes, there was a syntax error fix in `build_defs.bzl`, and we've moved back to the defaults-for-all `yes '' | configure` method.  

The failure with the `feature_column_test` must be random and unrelated to these mods.  I can temporarily disable that in `run_py3_core.sh` in a follow-on PR.

**Comment by whchung** [comment]
ok. let me merge this PR then and would be expecting a follow-up one.

**Pull request merged**
