### PR TITLE
Adding support for the new FP16 implementation in HIP

### PR DESCRIPTION
**Pull request by deven-amd**
This PR also replaces the code (in TF and Eigen) that uses the current FP16 implementation in HIP, with a version that is much less obtrusive.

We no longer need to modify code on the TF side (for either the current or the new FP16 implementation in HIP)

### CODE REVIEW

**Comment by whchung** [comment]
@parallelo do we have CI for TF 1.3 setup?

**Comment by whchung** [comment]
@deven-amd I haven't looked into `eigen.patch` yet so I've got some naive questions first.

to my understanding we use `HIP_VERSION_PATCH` to switch between legacy codes and new codes, but i don't see those changes in places such as  `tensorflow/core/framework/tensor.cc` or `tensorflow/core/lib/random/random_distributions.h`. could you explain the infrastructure within `eigen.patch` to make this possible?

**Comment by deven-amd** [comment]
@whchung 

I also changed the existing implementation so that we do not need any changes on the TF side anymore (whether it be the existing HIP FP16 implementation or the new HIP FP16 implementation).

The TF side of the code mostly uses Eigen::half API routines so it does not need to worry about the underlying implementation. The one exception to that *was* the access to the `Eigen::half.x` member which used to be `unsigned short` on the host side and `__half` on the device side. I changed that to be `unsigned short` on the device side (using the anonymous union trick Alex used in the new FP16 implementation :) ) so that we no longer need to special case the TF code.

The other (conceptually) major change is that we now have an implicit conversion operator (operator __half) defined to convert `Eigen::half` to the native `__fp16` for the existing HIP FP16 implementation. This allows us to not change code that calls the `__h*` HIP API routines that take `__fp16` arguments but are called with `Eigen::half` actuals in the Eigen code. 

In the new HIP FP16 implmentation, the `__h*` HIP API routines take `__half` arguments, and there exists a constructor to convert `__half _raw` to `__half` (and Eigen::half is derived from `__half_raw`)

**Comment by whchung** [comment]
@deven-amd Thanks for the clarification. It makes the patch easier to follow!

**Comment by parallelo** [comment]
run-jenkins-job

**Comment by whchung** [comment]
LGTM. I'd like to see how @parallelo could tune CI so we see a pass mark for this PR before merging it.

**Comment by parallelo** [comment]
Yep, currently working on _re-establishing_ a baseline for TF13's `rocm-v1` and TF18's `develop-upstream`.  Then, we'll filter out those failing tests -- that should help us to get CI in good initial shape.  After, we'll work on getting those baseline failures to pass and add them back into the collection of unit tests.

**Comment by whchung** [comment]
CI logs says:

```
[31m[1mERROR: [0mcommand succeeded, but there were loading phase errors.
```
I'll merge this PR anyhow.

**Comment by parallelo** [comment]
Just a heads-up, the last CI run was on June 4th.  Let me kick off another job, so we can check for any regressions.  It'll probably fail due to the ongoing XLA-related build errors, but at least we can check the unit tests.  

Jenkins:  retest this please

**Pull request merged**
