### PR TITLE
TESTING:  submitting a fresh PR to test Jenkins

### PR DESCRIPTION
**Pull request by parallelo**

### CODE REVIEW

**Comment by parallelo** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@parallelo is "Can one of the admins verify this patch?" generated by a bot?

CI log shows:
```
+ tensorflow/tools/ci_build/ci_build.sh ROCM ./tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
Invalid Dockerfile path: "/var/lib/jenkins/workspace/tensorflow-unit-tests/tensorflow/tools/ci_build/Dockerfile.rocm"
```

**Comment by parallelo** [comment]
Yes, it is a bot.  There are some additional settings for whitelisting..  (looking around for solutions, e.g. https://github.com/openzfs/openzfs-build/issues/21)

**Comment by parallelo** [comment]
@whchung - made some CI fixes, looking a bit better now

**Pull request closed without merging**
